customhost = "employee.ctert5snvebo.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "wongchithiam-employee"
customregion = "us-east-1"
